### ISSUE TITLE
Problem with "substring" when first rake db:migrate on CREATE INDEX

### ISSUE THREAD

**Issue by tomav** [robbyrussell/rubyurl#5]
Hi,

I have a problem whith "rake db:migrate"'.
Two first migrations are ok bit not the third one.

Here is the log :

[23:25:57] thomas@MacTom:~/Sites/local/rubyurl/config > rake db:migrate --trace
(in /Users/thomas/Sites/local/rubyurl)
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:migrate
== 3 AddIndexOnWebsiteUrl: migrating ==========================================
-- execute("CREATE INDEX website_url_index ON links ((substring(website_url, 0, 200)));")
rake aborted!
Mysql::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(substring(website_url, 0, 200)))' at line 1: CREATE INDEX website_url_index ON links ((substring(website_url, 0, 200)));
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:147:in `log'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:299:in `execute'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:330:in `send'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:330:in `method_missing'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:310:in `say_with_time'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:310:in `say_with_time'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:326:in `method_missing'
./db/migrate//003_add_index_on_website_url.rb:4:in `up_without_benchmarks'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:264:in `send'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:264:in `migrate'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:264:in `migrate'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:430:in `migrate'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:420:in `each'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:420:in `migrate'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:357:in `up'
/Users/thomas/Sites/local/rubyurl/vendor/rails/activerecord/lib/active_record/migration.rb:340:in `migrate'
/Users/thomas/Sites/local/rubyurl/vendor/rails/railties/lib/tasks/databases.rake:99
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Users/thomas/.gem/ruby/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

Tried on Debian and OSX with MySQL.

Any idea ? Many thanks, and nice job for the app.

**Comment by tomav** [comment]
Should be closed after 5 years :-)
